### ISSUE TITLE
Error in using Control Variables for Discrete Time Model

### ISSUE THREAD

**Issue by alokwarey** [dynamicslab/pysindy#107]
I have a fit a discrete time model with three control variables at each time step (u0, u1, u2). 

x0[k+1] = 0.040 1 + 0.991 x0[k] + -0.001 u0[k] + -0.002 u1[k] + 0.002 u2[k]

However, when I use model.simulate I get an error "control variables u must have same number of rows as x. u has 3 rows and x has 1 rows"

I am trying to pass a numpy array of control variables at each time step. Dimension (time, 3)

The documentation says: "If the model is discrete time, i.e. self.discrete_time == True, u should be a list (with len(u) == t) or array (with u.shape[0] == 1) giving the control inputs at each step."

How do I specify an array of shape 1 or list with three control variables? Should it be a list of length == t with each list entry a tuple of 3 or list of 3?

**Comment by briandesilva** [comment]
Try casting u as a list of length t: `u = list(u)`. I think this should solve the issue, but let me know if it doesn't.

**Comment by alokwarey** [comment]
Hi Brian,

Thanks so much! Still no luck. The issue is there are 3 control variables (u0, u1 and u2) at each time step. It works for continuous time, but not for discrete time.

The discrete time model is: 

x0[k+1] = 0.040 1 + 0.991 x0[k] + -0.001 u0[k] + -0.002 u1[k] + 0.002 u2[k]

I tried several options:

**Option 1:**
u = list(u), len(u) ==t

[array([-2.05435873, -4.66553167, -2.54354486]),
 array([-0.77291012, -4.65014286, -2.54355009]),
.
.
.]

**Option 2:**
u = list(map(tuple, u_train)), len(u) ==t

[(-2.0543587320548706, -4.665531668543994, -2.5435448572182477),
 (-0.7729101224030945, -4.650142860413386, -2.543550088453136),
 (-0.7729101224030945, -4.643040356467411, -2.54356502712129),
.
.
.
]

**Option 3:**
u = np.array (t,3), len(u) ==t

Got this error for all 3: control variables u must have same number of rows as x. u has 3 rows and x has 1 rows

**Comment by alokwarey** [comment]
I tried this as well: u = np.column_stack([u0, u1, u2]).

**Comment by alokwarey** [comment]
Any feedback on this?

**Comment by briandesilva** [comment]
Sorry for the slow reply. I'll investigate further and get back to you this evening.

**Comment by briandesilva** [comment]
Okay, it looks like I will need to implement a fix to address this. I'll let you know as soon as I've patched the issue (ETA Saturday).

**Comment by alokwarey** [comment]
Thanks!

**Comment by briandesilva** [comment]
@alokwarey, I've just merged a fix. To use the updated version you'll have to clone the package, and install it with `pip install .`. Or you could wait for the next PySINDy release on PyPI, where the fix will be included along with #106.

**Comment by briandesilva** [comment]
The changes are now available on PyPI. You should be able to pull the fix with ``pip install pysindy --upgrade``

**Comment by alokwarey** [comment]
@briandesilva : Thanks! Will upgrade and try it out.

**Comment by briandesilva** [comment]
@alokwarey, it looks like the release job is failing at the moment. You will need to get the changes by cloning the package for now.

**Comment by alokwarey** [comment]
I downloaded the latest release. it does work now. Thanks for the fix!
