### ISSUE TITLE
[BUG] self.n_input_features_ AttributeError -- (PySINDy doesn't work with scikit-learn 1.0)

### ISSUE THREAD

**Issue by A3EKV** [dynamicslab/pysindy#124]
Hello,
Today I have updated scikit-learn to version 1.0 and it seems that Pysindy is not compatible with this version yet.
Any plans to upgrade PySINDy to support sklearn 1.0?

Thank you

**Comment by akaptano** [comment]
We are planning a new release shortly (a few weeks) with lots of new SINDy functionality. I will try to fix this for the new release.

**Comment by akaptano** [comment]
Fixed this in the new release. Hopefully will get this out in a few weeks. For future reference, the issue is that scikit-learn 1.0 and beyond has decided that self.n_inputs_features_ should be called self.n_features_in_ so the fix is we have to check the scikit-learn version whenever assigning this variable for now.

**Comment by emanuele** [comment]
Hi, I see that this bug is still present in the master branch - I've just cloned and tried the [basic example of the guide](https://pysindy.readthedocs.io/en/latest/#example). What about fixing it by constraining the version of `scikit-learn` to be less than 1.0? Something like:
```
scikit-learn[alldeps]>=0.23, <1.0
```
in `requirements.txt`. It worked for me.

In any case, thank you for `pysindy`!! :)

**Comment by akaptano** [comment]
Hi Emanuele!

Glad you're using the code. You're right that this is an easy fix but we are waiting for the new release (hopefully here by the end of the week) where we have fixed the bug and allow for scikit-learn version 1.0 and above as well. Keep an eye out for that :)

**Comment by emanuele** [comment]
Thank you for the very good news!

**Comment by akaptano** [comment]
The new release is out, with a fix to this bug, so closing this issue now. Let me know if you encounter any more scikit-learn issues.
